[pytest]
pythonpath = src
markers =
    unit: mark test as a unit test
    integration: mark test as an integration test
    functional: mark test as a functional test

# In the top directory activate the virtual environment: source .venv/bin/activate
# Run command: python -m pytest [marker]